In [ ]:
%cd /home/alpaco/project/drunk_prj/models/rsj_model_euclid
!./run_all.shc

In [ ]:
!./run_all.sh train

In [ ]:
LOG_DIR="/home/alpaco/project/drunk_prj/models/rsj_model_euclid/log"
!mkdir -p "$LOG_DIR"  # 디렉터리가 없으면 생성
LOG_FILE="$LOG_DIR/log_$(date +'%Y-%m-%d_%H-%M-%S').txt"
# !python /home/alpaco/project/drunk_prj/models/rsj_model_euclid/train.py &> "$LOG_FILE"

!python /home/alpaco/project/drunk_prj/models/rsj_model_euclid/train.py

query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
y = 0 데이터 import 완료 
version:3.0, category : normal 
df.shape y=0 : (54224, 38) 
query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
y= 1 데이터 import 완료 
version:2.0, category : croki 
df.shape y=1 : (34580, 38) 
center_node
transform_keypoints
create_sequences
Coordinate columns: ['m1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', 'm5', 's5', 'm6', 's6', 'm7', 's7', 'm8', 's8', 'm9', 's9', 'm10', 's10', 'm11', 's11', 'm12', 's12', 'm13', 's13', 'm14', 's14', 'm15', 's15', 'm16', 's16', 'm17', 's17', 'y']
Target column: y
Label column: label
filename column: filename
Data columns: ['m1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', 'm5', 's5', 'm6', 's6', 'm7', 's7', 'm8', 's8', 'm9', 's9', 'm10', 's10', 'm11', 's11', 'm12', 's12', 'm13', 's13', 'm14', 's14', 'm15', 's15', 'm16', 's16', 'm17', 's17', 'label', 'filename', 'y', 'xm', 'ym']
Using columns for sequences: ['m1', 's1', 'm2', 's2', 'm3', 's3', '

In [2]:
!pwd

/home/alpaco/project/drunk_prj/models/rsj_model_euclid


In [ ]:
from train import testing
path = '';
testing();

In [9]:
# train.py

import torch
import pandas as pd

from datetime import datetime
from torch.utils.data import TensorDataset, DataLoader

# 프로젝트 구성 요소 임포트
from config.config import DATA_CONFIG, MODEL_CONFIG, TRAINING_CONFIG, config_path


from util.util import (
    load_data,
    center_node,
    transform_keypoints,
    create_sequences,
    train_test_set
)

from  util.data_import import import_df,import_df_db

from model.lstm_model import (
    BinaryLSTMModel,
    evaluate,
    train_model,
    save_model_and_config,
    evaluate_and_save_confusion_matrix
)


# 디바이스 설정: CUDA 또는 CPU
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

# 데이터 경로 및 시퀀스 길이 설정
data_path = DATA_CONFIG["data_path"]
print(f"Data path: {data_path}")

# CSV 파일 읽어오기
# df = pd.read_csv(data_path)

# df = import_df()

df = import_df_db(2.0)

# 키포인트 데이터의 중심점 계산
xm, ym = center_node(df)

# 키포인트 데이터를 기울기와 유클리드 거리로 변환
mdf = transform_keypoints(df, xm, ym)

# 시퀀스 데이터 생성
seq_length = DATA_CONFIG["seq_length"]
X_seq, y_seq = create_sequences(mdf, seq_length)
print("X_seq shape:", X_seq.shape)  # 입력 데이터 형태 확인
print("y_seq shape:", y_seq.shape)  # 타겟 데이터 형태 확인

# 데이터셋 분리 및 DataLoader 생성
train_loader, valid_loader = train_test_set(X_seq, y_seq)

# 모델 학습
model = train_model(train_loader, valid_loader, X_seq, device)

# 학습된 모델과 설정 저장
save_dir = save_model_and_config(model)



Data path: /home/alpaco/project/drunk_prj/models/rsj_model_euclid/testdata/618-8_cam01_drunken01_place03_night_spring_4102_4957_totter.csv
center_node
transform_keypoints
create_sequences
Coordinate columns: ['xm', 'ym', 'm1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', 'm5', 's5', 'm6', 's6', 'm7', 's7', 'm8', 's8', 'm9', 's9', 'm10', 's10', 'm11', 's11', 'm12', 's12', 'm13', 's13', 'm14', 's14', 'm15', 's15', 'm16', 's16', 'm17', 's17', 'y']
Target column: y
Label column: label
Data columns: ['m1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', 'm5', 's5', 'm6', 's6', 'm7', 's7', 'm8', 's8', 'm9', 's9', 'm10', 's10', 'm11', 's11', 'm12', 's12', 'm13', 's13', 'm14', 's14', 'm15', 's15', 'm16', 's16', 'm17', 's17', 'label', 'y', 'xm', 'ym']
Using columns for sequences: ['xm', 'ym', 'm1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', 'm5', 's5', 'm6', 's6', 'm7', 's7', 'm8', 's8', 'm9', 's9', 'm10', 's10', 'm11', 's11', 'm12', 's12', 'm13', 's13', 'm14', 's14', 'm15', 's15', 'm16', 's16', 'm17', '

In [ ]:
def_data_insert_table

[[[-739.5 -356.0 0.587 ... 0.76 980.219 1.0]
  [-737.5 -354.0 0.592 ... 0.759 976.015 1.0]
  [-736.5 -350.5 0.5 ... 0.749 970.1 1.0]
  ...
  [37.5 119.5 -19.222 ... -10.13 117.066 1.0]
  [37.0 119.5 -45.25 ... -10.5 116.023 1.0]
  [41.0 118.0 88.0 ... -7.533 113.991 1.0]]

 [[-737.5 -354.0 0.592 ... 0.759 976.015 1.0]
  [-736.5 -350.5 0.5 ... 0.749 970.1 1.0]
  [-729.0 -349.5 0.597 ... 0.763 958.533 1.0]
  ...
  [37.0 119.5 -45.25 ... -10.5 116.023 1.0]
  [41.0 118.0 88.0 ... -7.533 113.991 1.0]
  [38.5 116.5 -58.333 ... -7.258 113.563 1.0]]

 [[-736.5 -350.5 0.5 ... 0.749 970.1 1.0]
  [-729.0 -349.5 0.597 ... 0.763 958.533 1.0]
  [-727.5 -348.5 0.496 ... 0.759 954.917 1.0]
  ...
  [41.0 118.0 88.0 ... -7.533 113.991 1.0]
  [38.5 116.5 -58.333 ... -7.258 113.563 1.0]
  [37.5 120.5 -36.6 ... -7.065 110.592 1.0]]

 ...

 [[115.0 312.0 0.239 ... 11.955 263.919 1]
  [110.5 314.5 0.239 ... 9.473 261.948 1]
  [110.5 314.0 0.239 ... 6.444 264.124 1]
  ...
  [-998.0 65.0 0.25 ... 0.438 1290.52

In [ ]:
from  util.data_import import import_df,import_df_db
from util.def_data_insert_table import import_data ,temp

version = '1.0'
major_category = 'abs'
df = import_data(version, major_category)


        frame  x1  y1  x2  y2  x3  y3  x4  y4    x5  ...  y14  x15  y15  x16  \
0           1   0   0   0   0   0   0   0   0    76  ...  377  118  356   81   
1           2   0   0   0   0   0   0   0   0    76  ...  368   98  364  113   
2           3  95  52   0   0  86  44   0   0    63  ...  360   75  376  142   
3           4  94  53   0   0  86  44   0   0    66  ...  361   81  375  139   
4           5  92  52   0   0  82  44   0   0    59  ...  355   70  375  143   
...       ...  ..  ..  ..  ..  ..  ..  ..  ..   ...  ...  ...  ...  ...  ...   
635462    924  55  61  56  45  44  56  86  17 -1369  ...  304  117  266  194   
635463    925  51  52  53  35  38  47  84  12 -1372  ...  299  114  263  192   
635464    926  50  41  55  24  38  35  88  10 -1373  ...  298  115  263  193   
635465    927  49  40  54  22  36  34  87   9 -1373  ...  297  114  263  193   
635466    928  52  45  55  28  39  41  86  11 -1372  ...  297  117  262  193   

        y16  x17  y17       label  \
0 

In [20]:
from util.def_data_insert_table import import_data ,temp


ImportError: cannot import name 'temp' from 'util.def_data_insert_table' (/home/alpaco/project/drunk_prj/models/rsj_model_euclid/util/def_data_insert_table.py)

In [ ]:
folder_path = "/home/alpaco/project/drunk_prj/data/comfirm_video1/totter/Rel"

version = '2.0'
major_category = 'abs'
sub_category =''

data_inserter.insert_data(folder_path , version, major_category, sub_category)

In [4]:
from util.data_import import import_data
version = '2.0'
category = 'croki'
sub_category ='abs1'

df = import_data(version, category)
# df['label'] = df['label'].astype(str).str.replace("[: ]", "", regex=True)
df['y'] = 1
print(df['filename'])

query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
0        209-5_cam02_drunken01_place03_night_spring_503...
1        209-5_cam02_drunken01_place03_night_spring_503...
2        209-5_cam02_drunken01_place03_night_spring_503...
3        209-5_cam02_drunken01_place03_night_spring_503...
4        209-5_cam02_drunken01_place03_night_spring_503...
                               ...                        
34575    212-5_cam02_drunken03_place03_night_summer_167...
34576    212-5_cam02_drunken03_place03_night_summer_167...
34577    212-5_cam02_drunken03_place03_night_summer_167...
34578    212-5_cam02_drunken03_place03_night_summer_167...
34579    212-5_cam02_drunken03_place03_night_summer_167...
Name: filename, Length: 34580, dtype: object


In [3]:

from util.data_import import import_data
version = '2.0'
category = 'normal'

df = import_data(version, category)
df['label'] = df['label'].astype(str).str.replace("[: ]", "", regex=True)
df['y'] = 0
print(df['filename'])

query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
0         C_32_7_smp_su_09-11_11-01-00_c_for_DF2_(53_143)
1         C_32_7_smp_su_09-11_11-01-00_c_for_DF2_(53_143)
2         C_32_7_smp_su_09-11_11-01-00_c_for_DF2_(53_143)
3         C_32_7_smp_su_09-11_11-01-00_c_for_DF2_(53_143)
4         C_32_7_smp_su_09-11_11-01-00_c_for_DF2_(53_143)
                               ...                       
102370    C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
102371    C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
102372    C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
102373    C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
102374    C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
Name: filename, Length: 102375, dtype: object


In [1]:
# train.py

import torch
import pandas as pd

from datetime import datetime
from torch.utils.data import TensorDataset, DataLoader

# 프로젝트 구성 요소 임포트
from config.config import DATA_CONFIG, MODEL_CONFIG, TRAINING_CONFIG, config_path


from util.util import (
    load_data,
    center_node,
    transform_keypoints,
    create_sequences,
    train_test_set
)

from  util.def_data_insert_table import import_data

from model.lstm_model import (
    BinaryLSTMModel,
    evaluate,
    train_model,
    save_model_and_config,
    evaluate_and_save_confusion_matrix
)

from util.data_import import import_data
import pandas as pd
version = '2.0'
category = 'normal'

df_n = import_data(version, category)
df_n['y'] = 0
category = 'croki'

df_c = import_data(version, category)
df_c['y'] = 1


# 1. 공통 컬럼 추출
common_columns = df_c.columns.intersection(df_n.columns)

# 2. 공통 컬럼만 유지
df1_filtered = df_c[common_columns]
df2_filtered = df_n[common_columns]

# 3. 위아래로 결합 (concat)
df = pd.concat([df1_filtered, df2_filtered], ignore_index=True)

# 키포인트 데이터의 중심점 계산
xm, ym = center_node(df)

mdf = transform_keypoints(df, xm, ym)

# 시퀀스 데이터 생성
seq_length = DATA_CONFIG["seq_length"]
print(mdf['filename'])
X_seq, y_seq = create_sequences(mdf, seq_length)


query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
query: SELECT data FROM csv_data WHERE version = %s AND category = %s 
center_node
transform_keypoints
0         209-5_cam02_drunken01_place03_night_spring_503...
1         209-5_cam02_drunken01_place03_night_spring_503...
2         209-5_cam02_drunken01_place03_night_spring_503...
3         209-5_cam02_drunken01_place03_night_spring_503...
4         209-5_cam02_drunken01_place03_night_spring_503...
                                ...                        
136950      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136951      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136952      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136953      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136954      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
Name: filename, Length: 136955, dtype: object
create_sequences
Coordinate columns: ['label', 'filename', 'xm', 'ym', 'm1', 's1', 'm2', 's2', 'm3', 's3', 'm4', 's4', '

In [10]:
df['filename']

0         209-5_cam02_drunken01_place03_night_spring_503...
1         209-5_cam02_drunken01_place03_night_spring_503...
2         209-5_cam02_drunken01_place03_night_spring_503...
3         209-5_cam02_drunken01_place03_night_spring_503...
4         209-5_cam02_drunken01_place03_night_spring_503...
                                ...                        
136950      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136951      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136952      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136953      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
136954      C_32_8_smp_su_09-11_11-27-00_a_for_DF2_(56_146)
Name: filename, Length: 136955, dtype: object